const state = {
  includeEmbeds: true,
  includeCollapsed: false,
  excludeDuplicate: false,
  displayBefore: false,
  iziToastPosition: undefined,
  showPath: true,
  wholeGraph: undefined,
  highlightColor: undefined,
  matchesSortedBy: "page",
  extractMatchesOnly: true,
  codeBlockLimit: 150,
  iziToastColor: "#262626F0",

  selectionBlue: undefined,
  lastOperation: "",
  changesNb: 0,
  changesNbBackup: undefined,
  isPrepending: undefined,
  workspace: undefined,
  formatChange: false,
  expandedNodesUid: [],
  collapsedNodesUid: [],
  referencedNodesUid: [],
  uniqueReferences: [],
  notExpandedNodesUid: [],
  selectedBlocks: [],
  modifiedBlocksCopy: [],
  inputBackup: [],
  refsUids: [],
  eltFound: undefined,
  currentToast: null,
  scrollIndex: 0,
  matchIndex: 0,
  matchArray: [],
  matchingStringsArray: [],
  matchRefsArray: undefined,
  matchingTotal: 0,
  matchingHidden: 0,
  ANDwithChildren: false,
  textToCopy: undefined,

  // Dialog shared vars (used by formDialog)
  resultsJSX: undefined,
  dialogTitle: undefined,
  submitParams: undefined,
  handleSubmit: undefined,
};
export default state;
